version: '3'

services:
  postgres12:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ~/developer/docker/postgres/12:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "5454:80"
    depends_on:
      - postgres12
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge